final searchPlaceHolders = [
  "Doctor's Dilemma",
  "Oliver Twist",
  "Julius Caesar",
  "Journeys to Bagdad",
  "Hamlet",
  "Evangeline",
  "Piano and Song",
  "Parables from Nature",
  "American Senator",
  "Retired Cat",
  "Fool There Was",
  "Crown for Joanna",
  "Americans and Others",
  "Poor Miss Finch",
  "Love's Wantonness",
  "Pirates Own Book",
  "Miss Marjoribanks",
  "Willows",
  "Man in the Moone",
  "Weapons of Mystery",
  "Family of Love",
  "Carmilla",
  "Sailor's Lass",
  "Six Stories",
  "The Colour of Life",
  "Sacred Meditations",
  "Manfred",
  "Amethyst Box",
  "Old Rose And Silver",
  "Vampire",
  "Guide to Men",
  "British Barbarians",
  "Orange Fairy Book",
  "Make-Believe Man",
  "Victorian Literature",
  "Erotica Romana",
  "Yollop",
  "Apology",
  "Castle Richmond",
  "Skin Game",
  "Contra Gentes",
  "K-Factor",
  "Shropshire Lad",
];
